The GraalVM support has been improved in Micronaut 2.1.0 with the new https://github.com/micronaut-projects/micronaut-gradle-plugin[Micronaut Gradle Plugin]
so now everything is configured by the plugin and you don't need to do anything to your application or select the
`graalvm` feature when creating the application.


=== Installing GraalVM

The first step is installing GraalVM via the https://www.graalvm.org/docs/getting-started/[Getting Started] instructions or using SDKman:

.Installing GraalVM 20.2.0 with SDKman
[source,bash]
----
$ sdk install java 20.2.0.r8-grl # or 20.2.0.r11-grl for JDK 11
----

The `native-image` tool was extracted from the base GraalVM distribution. Currently, it is available as an early adopter plugin. To install it, run:

.Installing `native-image` tool
[source,bash]
----
$ gu install native-image # <1>
----
<1> You only need to do that the first time to install the `native-image` tool.


=== Creating native image outside Docker

To build your native image without using Docker is now really simple:

.Building Graal native image
[source,bash]
----
$ sdk use java 20.2.0.r8-grl

$ ./gradlew nativeImage
----

The previous command will create the native executable `build/native-image/application`.

It is also possible to customize the name of the native image or pass additional parameters to GraalVM:

.build.gradle
[source,groovy]
----
nativeImage {
    args('--verbose')
    imageName('micronaut-graalvm-app') // <1>
}
----
<1> The native image name will now be `micronaut-graalvm-app`


=== Creating native image inside Docker

The output following this approach is a docker image that runs the native image of your application. You don't need to install
any additional dependency.

.Building Graal native image
[source,bash]
----
$ sdk use java 20.2.0.r8-grl

$ ./gradlew dockerBuildNative
----

The previous command will create the image `complete:latest`. To execute it:

.Executing the native image
[source,bash]
----
$ docker run -p 8080:8080 complete
10:29:46.845 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 12ms. Server Running: http://localhost:8080
----

We can see that the application starts in only 12ms.


=== Sending a request

Start the application either using Docker or the native executable. You can run a few cURL requests to test the application:

[source,bash]
----
complete $ time curl localhost:8080/conferences/random
{"name":"Greach"}
real    0m0.016s
user    0m0.005s
sys     0m0.004s

complete $ time curl localhost:8080/conferences/random
{"name":"GR8Conf EU"}
real    0m0.014s
user    0m0.005s
sys     0m0.004s

----

NOTE: For more information about the new Micronaut Gradle plugin, take a look at https://github.com/micronaut-projects/micronaut-gradle-plugin[the documentation].
