When we created the application we used the `graal-native-image` feature. This feature adds three important items:

1.- `svm` and `graal` dependencies in `build.gradle`:

.build.gradle
[source,groovy]
----
include::{sourceDir}/build.gradle[tag=graal,indent=0]
----
<1> Annotation processor to generate the `reflect` information at compile time.

2.- A `Dockerfile` which can be used to construct the native image executing `docker-build.sh`

3.- A `native-image.properties` file in `resources/META-INF/native-image/example.micronaut/complete-application` directory with
Graal's `native-image` configuration. This file can be used to fine tune the native-image generation.

.native-image.properties
[source]
----
include::{sourceDir}/src/main/resources/META-INF/native-image/example.micronaut/complete-application/native-image.properties[]
----


=== Creating native image inside Docker

With this approach you only need to build the fatjar and then use Docker to build the native image.

.Building Graal native image
[source,bash]
----
$ ./docker-build.sh
----

The previous command will create the image `complete:latest`. To execute it:

.Executing the native image
[source,bash]
----
$ docker run --network host complete
10:29:46.845 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 12ms. Server Running: http://nobita:8080
----

We can see that the application starts in only 12ms.

TIP: We use the option `--network host` to use the same network as the host and expose automatically all the ports


=== Creating native image outside Docker

NOTE: For this approach you need to use Linux or Mac. As this moment GraalVM is not supported on Windows.

.Building Graal native image
[source,bash]
----
$ sdk use java 1.0.0-rc-14-grl
$ ./gradlew assemble
$ native-image --no-server -cp build/libs/complete-*.jar
----

The previous commmand will create a native executable called `complete`.


=== Sending a request

Start the application either using Docker or the native executable. You can run a few cURL requests to test the application:

[source,bash]
----
complete $ time curl localhost:8080/conferences/random
{"name":"Oracle Code One"}
real    0m0.016s
user    0m0.005s
sys     0m0.004s

complete $ time curl localhost:8080/conferences/random
{"name":"GR8Conf EU"}
real    0m0.014s
user    0m0.005s
sys     0m0.004s

----
