The GraalVM support has been improved in Micronaut 2.2.0 with a new https://micronaut-projects.github.io/micronaut-maven-plugin/latest/index.html[Micronaut Maven Plugin]
and Micronaut 2.1.0 already included a https://github.com/micronaut-projects/micronaut-gradle-plugin[Micronaut Gradle Plugin].

Now everything is configured by the plugins and you don't need to do anything to your application or select the
`graalvm` feature when creating the application.

NOTE: This guide uses Gradle but it contains instructions for using the Maven plugin. To create the application with Maven
support run: `mn create-app hello-world --build maven`.

=== Installing GraalVM

The first step is installing GraalVM via the https://www.graalvm.org/docs/getting-started/[Getting Started] instructions or using SDKman:

.Installing GraalVM 20.3.0 with SDKman
[source,bash]
----
$ sdk install java 20.3.0.r8-grl # or 20.3.0.r11-grl for JDK 11
----

The `native-image` tool was extracted from the base GraalVM distribution. Currently, it is available as an early adopter plugin. To install it, run:

.Installing `native-image` tool
[source,bash]
----
$ gu install native-image # <1>
----
<1> You only need to do that the first time to install the `native-image` tool.


=== Creating native image outside Docker

To build your native image without using Docker is now really simple:

.Building Graal native image
[source,bash]
----
$ sdk use java 20.3.0.r8-grl

$ ./gradlew nativeImage
----

Or if you use Maven:
[source,bash]
----
$ sdk use java 20.3.0.r8-grl

$ ./mvnw package -Dpackaging=native-image
----

The previous command will create the native executable in `build/native-image` directory (or in `target` if you use Maven).

It is also possible to customize the name of the native image or pass additional parameters to GraalVM:

.build.gradle
[source,groovy]
----
nativeImage {
    args('--verbose')
    imageName('hello-world') // <1>
}
----
<1> The native image name will now be `micronaut-graalvm-app`


=== Creating native image inside Docker

The output following this approach is a docker image that runs the native image of your application. You don't need to install
any additional dependency.

.Building Graal native image
[source,bash]
----
$ ./gradlew dockerBuildNative
----

.Building Graal native image with Maven
[source,bash]
----
$ ./mvnw package -Dpackaging=docker-native
----

The previous command will create the image `hello-world:latest`. To execute it:

.Executing the native image
[source,bash]
----
$ docker run -p 8080:8080 complete
10:29:46.845 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 12ms. Server Running: http://localhost:8080
----

We can see that the application starts in only 12ms.


=== Sending a request

Start the application either using Docker or the native executable. You can run a few cURL requests to test the application:

[source,bash]
----
complete $ time curl localhost:8080/conferences/random
{"name":"Greach"}
real    0m0.016s
user    0m0.005s
sys     0m0.004s

complete $ time curl localhost:8080/conferences/random
{"name":"GR8Conf EU"}
real    0m0.014s
user    0m0.005s
sys     0m0.004s

----

NOTE: For more information about the new plugins take a look at the https://github.com/micronaut-projects/micronaut-gradle-plugin[Micronaut Gradle plugin]
and https://micronaut-projects.github.io/micronaut-maven-plugin/latest/index.html[Micronaut Maven Plugin] documentation.
