When we created the application we used the `graal-native-image` feature. This feature adds three important items:

1.- `svm` and `graal` dependencies in `build.gradle`:

.build.gradle
[source,groovy]
----
include::{sourceDir}/build.gradle[tag=graal,indent=0]
----
<1> Annotation processor to generate the `reflect` information at compile time.

2.- A `Dockerfile` which can be used to construct the native image executing `docker-build.sh`

3.- A `native-image.properties` file in `resources/META-INF/native-image/example.micronaut/complete-application` directory with
Graal's `native-image` configuration. This file can be used to fine tune the native-image generation.

.native-image.properties
[source]
----
include::{sourceDir}/src/main/resources/META-INF/native-image/example.micronaut/complete-application/native-image.properties[]
----


=== Creating native image inside Docker

With this approach you only need to build the fatjar and then use Docker to build the native image.

.Building Graal native image
[source,bash]
----
$ ./gradlew assemble
$ ./docker-build.sh
----

The previous command will create the image `micronaut-graal-app:latest`. To execute it:

.Executing the native image
[source,bash]
----
$ docker run -p 8080:8080 micronaut-graal-app
10:29:46.845 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 12ms. Server Running: http://localhost:8080
----

We can see that the application starts in only 12ms.


=== Creating native image outside Docker

To build your native image without using Docker you need to install GraalVM SDK via the https://www.graalvm.org/docs/getting-started/[Getting Started] instructions or using SDKman:

.Installing GraalVM 19.2.0 with SDKman
[source,bash]
----
$ sdk install java 19.2.0-grl
$ sdk use java 19.2.0-grl
----

The `native-image` tool was extracted from the base GraalVM distribution. Currently it is available as an early adopter plugin. To install it, run:

.Installing `native-image` tool
[source,bash]
----
$ gu install native-image # <1>
----
<1> You only need to do that the first time to install the `native-image` tool.


.Building Graal native image
[source,bash]
----
$ sdk use java 19.2.0-grl
$ ./gradlew assemble
$ native-image --no-server -cp build/libs/complete-*-all.jar # <1>
----
<1> Starting in Micronaut 1.1.0 it is really simple to create the native image.

The previous commmand will create a native executable called `micronaut-graal-app`.


=== Sending a request

Start the application either using Docker or the native executable. You can run a few cURL requests to test the application:

[source,bash]
----
complete $ time curl localhost:8080/conferences/random
{"name":"Greach"}
real    0m0.016s
user    0m0.005s
sys     0m0.004s

complete $ time curl localhost:8080/conferences/random
{"name":"GR8Conf EU"}
real    0m0.014s
user    0m0.005s
sys     0m0.004s

----
